### ISSUE TITLE
How To Use in Ionic 2.0 Framework

### ISSUE THREAD

**Issue by jonbongato** [an-rahulpandey/ios-audio-picker#11]
Hi, I am a bit new to this, but I was wondering if you had any suggestions as to how this could be implemented or imported over onto the Ionic 2.0 framework. Much appreciated, thanks!

**Comment by WinGood** [comment]
Hello, i hope next code will help you:

```
// above import declarations  
declare var window;

@Component({
  selector: 'component',
  templateUrl: 'component.html'
})

export class Component {
  method() {
    window.plugins.mediapicker.getAudio();
  }
}
```

**Comment by an-rahulpandey** [comment]
Sorry....didn't start with Ionic 2 yet. What is happening there, is it calling the plugin method, but plugin not opening the media picker or it is not at all calling the plugin method. Try to put console log in plugin js file.

**Comment by ScottMBerger** [comment]
I have it working well with Ionic 2 without any issues besides for needing to add the media privacy in the info.plist. 

The only problem I have with it is that I would like some callback that is triggered when the user either selects a song or cancels the picker. I want to add a loader for the time between when someone picks the song and it is ready because this can take 2 to 5 seconds to get the exported URL.

**Comment by an-rahulpandey** [comment]
Hi,
Check out the media picker plugin https://github.com/an-rahulpandey/cordova-plugin-mediapicker
