### ISSUE TITLE
iOS 8.4 und 8.4.1

### ISSUE THREAD

**Issue by gustav77** [an-rahulpandey/ios-audio-picker#4]
Hi,

tried to use your plugin but with no success. I took your demo and deployed it to an iPod (iOS 8.4) and an iPad (iOS 8.4.1). 

On both devices the app shows up, but nothing happens, when I clicked "Select Audio".

Any idea?
Guenter

**Comment by an-rahulpandey** [comment]
Hi,

Will you be able to provide me with some debug data?

**Comment by gustav77** [comment]
First I had a simple typo, sorry for that.

Now I can select a audio file from apple music, as you see I got the download completed, but when I try to play the song there is this unknown resource message: 

2015-09-15 17:09:44.854 Dressage[689:216064] AVAssetExportSessionStatusCompleted file:///var/mobile/Containers/Data/Application/21B5DFAD-888F-48C5-9D17-EF1FCABAA08D/Documents/Alone.m4a
2015-09-15 17:09:44.887 Dressage[689:216064] Export Completed = 1 out of Total Selected = 1
2015-09-15 17:09:52.420 Dressage[689:215113] Will attempt to use file resource 'file:///var/mobile/Containers/Data/Application/21B5DFAD-888F-48C5-9D17-EF1FCABAA08D/Documents/Alone.m4a'
2015-09-15 17:09:52.421 Dressage[689:215113] Unknown resource 'file:///var/mobile/Containers/Data/Application/21B5DFAD-888F-48C5-9D17-EF1FCABAA08D/Documents/Alone.m4a'
(lldb)

**Comment by an-rahulpandey** [comment]
Can you try to play it using the cdvfile protocol?
https://github.com/apache/cordova-plugin-file#cdvfile-protocol
https://github.com/apache/cordova-plugin-media#media

**Comment by gustav77** [comment]
Yes this works for me. Thank you.

**Comment by an-rahulpandey** [comment]
Will you be able to send a pull request for the changes in demo?

**Comment by jonbongato** [comment]
@gustav77 do you mind sharing exactly how you did this (trying to play with the cdvfile protocol)? I've been getting the same issue.

**Comment by an-rahulpandey** [comment]
@jonbongato Currently in demo the song url starting with file:/// is getting replaced by just '/', so that the media plugin (old version) can play the song using the following url format /var/localhost/mobile.........

The audio picker plugin stores the song in Document folder after converting and in the latest file plugin that path can be accessed by cdvfile://localhost/ (please check it first). Therefore you have to replace the path till Documents folder using cdvfile://localhost while playing the song. 
I do not have access to Mac right now, otherwise I would have checked and updated the code. If you get it working please send a PR.
